### PR TITLE
Refactor api

### PR DESCRIPTION
**Pull request by yangkcatiu**
Sorry for the large PR. Here are what it inlcudes:

1. Move oauth, fields, expansions to their dedicated py files
2. Create `UserExpansions` and `TweetExpansions` classes
3. Adopt the new fields and expansions model in all endpoints

In my view, the code is much clear now and it will be easier to add new endpoints for the future.

### CODE REVIEW

**Comment by mr-devs** [comment]
This looks awesome! I will review it when I get a chance. FYI, I am just going to need some time and probably won't have it until the weekend.

**Comment by yangkcatiu** [comment]
Take your time. I won't add any new functions/classes any time soon. Just need to work on the documentation a little big.

**Comment by yangkcatiu** [comment]
Just to want to check in and make sure that this is still on your plate @mr-devs . I'm hoping to bump the pip version after we merge this PR and do some advertisement on social media. But no rush.

**Comment by mr-devs** [comment]
I hear you. Yes, this is on my to-do list. I was planning on getting to it Saturday. Sorry, the vaccines stuff has really really snowballed beyond what I intended to get involved with and has set me back on a bunch of other stuff that I am not trying to catch up on.

**Comment by yangkcatiu** [comment]
Don't worry and no rush. You are doing great!

**Review by mr-devs — APPROVED** [review]
Looks good to me, will merge now. 

Great work!

**Pull request merged**
